# Generated by Django 5.2.8 on 2026-02-13 13:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='only letters are valid', regex="^[A-Za-z,.']+")], verbose_name='Product Name')),
                ('category', models.IntegerField(choices=[(1, 'Vegetable'), (2, 'Fruit')], default=1, verbose_name='Product Category')),
                ('discription', models.TextField(max_length=500, validators=[django.core.validators.RegexValidator(message='only letters are valid', regex="^[A-Za-z,.']+")], verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Product Price')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Available Price')),
                ('status', models.IntegerField(choices=[(1, 'instock'), (2, 'outofstock')], default=1, verbose_name="Product's Status")),
                ('product_Img', models.ImageField(default='images/products/vv.jpg', upload_to='images/products/', verbose_name='Product Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
