# Generated by Django 5.2.8 on 2026-02-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_orders', '0002_initial'),
        ('app_products', '0001_initial'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='consumers',
            field=models.ManyToManyField(related_name='consumers', through='app_orders.Orders', to='app_users.profile'),
        ),
    ]
