# Generated by Django 5.2.8 on 2026-02-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_cart'),
        ('app_users', '0002_profile_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('profile', 'product')},
        ),
    ]
