# Generated by Django 5.2.8 on 2026-05-16 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_rename_user_cart_profile_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Available stock'),
        ),
    ]
