# Generated by Django 5.2.8 on 2026-06-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='consumers',
        ),
    ]
