# Generated by Django 5.2.8 on 2026-08-16 08:00

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0008_alter_cart_created_at_alter_cart_updated_at_and_more'),
        ('app_users', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('profile', 'product', 'created_at')},
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('created_at'), models.F('profile'), models.F('product'), name='unique_user_per_day'),
        ),
    ]
