# Generated by Django 5.2.8 on 2026-08-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0009_alter_cart_unique_together_cart_unique_user_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
