# Generated by Django 5.2.8 on 2026-09-08 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0010_rename_discription_product_description'),
        ('app_users', '0009_alter_profile_fname_alter_profile_lname'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_user_per_day',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.RegexValidator(message="only letters and (,-'!#%&()) and space are allowed", regex="^[A-Za-z-'!#%&(), ]+")], verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="only letters and (- ') and space are allowed", regex="^[A-Za-z-' ]+")], verbose_name='Product Name'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('profile', 'product')},
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(models.F('profile'), models.F('product'), name='unique_product_per_profile'),
        ),
    ]
