# Generated by Django 5.2.8 on 2026-09-08 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogLocation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_position', models.PositiveBigIntegerField()),
                ('length', models.PositiveBigIntegerField()),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='base.logfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogIndex',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='base.loglocation')),
            ],
            options={
                'indexes': [models.Index(fields=['attribute_name', 'attribute_value'], name='logindex_attr_value_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'attribute_name', 'attribute_value'), name='unique_log_index_entry')],
            },
        ),
    ]
