# Generated by Django 5.2.8 on 2026-09-14 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='file_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Logfile Signature ID format. Must follow SHA256 signature.', regex='^[a-fA-F0-9]{64}$')]),
        ),
        migrations.AddField(
            model_name='logfile',
            name='file_modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='logfile',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='file size'),
        ),
    ]
