# Generated by Django 5.2.8 on 2026-09-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_logfile_file_fingerprint_logfile_file_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='file_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
