# Generated by Django 5.2.8 on 2026-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_cart'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='profiles', through='app_products.Cart', to='app_products.product'),
        ),
    ]
