# Generated by Django 5.2.8 on 2026-05-16 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_profile_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='only numbers and letters are valid', regex='^[A-Za-z0-9]{6,}')], verbose_name='verification code'),
        ),
    ]
