# Generated by Django 5.2.8 on 2026-05-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0002_alter_location_city_alter_location_hno_and_more'),
        ('app_users', '0003_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app_locations.location', verbose_name='location'),
        ),
    ]
