# Generated by Django 5.2.8 on 2026-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0003_location_is_homeaddress'),
        ('app_users', '0004_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='location', to='app_locations.location', verbose_name='location'),
        ),
    ]
