# Generated by Django 5.2.8 on 2026-08-11 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0004_alter_location_created_at_alter_location_updated_at'),
        ('app_products', '0008_alter_cart_created_at_alter_cart_updated_at_and_more'),
        ('app_users', '0006_alter_emailverificationcode_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, default=None, related_name='profiles', through='app_products.Cart', to='app_products.product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ManyToManyField(blank=True, default=None, related_name='location', to='app_locations.location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='only numbers are valid and only 10 digits are allowed', regex='^[0-9]{10,}')], verbose_name='mobile no.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='invalid email', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')], verbose_name='email'),
        ),
    ]
