# Generated by Django 5.2.8 on 2026-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_alter_profile_cart_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Worker'), (3, 'Consumer')], default=3, verbose_name='role'),
        ),
    ]
