# Generated by Django 5.2.8 on 2026-09-08 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='only letters and spaces are valid', regex='^[A-Za-z ]+')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(message='only letters and spaces are valid', regex='^[A-Za-z ]+')], verbose_name='last name'),
        ),
    ]
