# Generated by Django 5.2.8 on 2026-06-08 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_initial'),
        ('app_products', '0007_remove_product_consumers'),
        ('app_users', '0005_remove_profile_location_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_paid',
            field=models.IntegerField(default=0, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedby', to='app_users.profile', verbose_name='Consumer'),
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('total_price', models.IntegerField(verbose_name='total_price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('refunded', 'Refunded'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='app_orders.orders', verbose_name='Order')),
                ('ordered_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_item', to='app_products.product', verbose_name='Ordered Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
