# Generated by Django 5.2.8 on 2026-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_remove_orders_amount_paid_orders_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
