# Generated by Django 5.2.8 on 2026-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0005_alter_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20),
        ),
    ]
