# Generated by Django 5.2.8 on 2026-07-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0007_alter_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='status',
            new_name='item_status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid'), ('expired', 'Expired')], default='not_paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
