# Generated by Django 5.2.8 on 2026-08-11 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0009_alter_ordereditem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='item_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('refunded', 'Refunded'), ('delayed', 'Delayed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('refund_amount', models.PositiveIntegerField(default=0, verbose_name='refunded_amount')),
                ('refund_status', models.CharField(choices=[('processed', 'Processed'), ('pending', 'Pending'), ('failed', 'Failed'), ('initiated', 'Initiated')], default='pending', max_length=20)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='app_orders.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
