# Generated by Django 5.2.8 on 2026-09-08 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0010_alter_ordereditem_item_status_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='total_price',
            field=models.PositiveIntegerField(default=1, verbose_name='total_price'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Invalid Razorpay Order ID format. Must start with 'order_' followed by alphanumeric characters.", regex='^order_[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Invalid Razorpay Payment ID format. Must start with 'pay_' followed by alphanumeric characters.", regex='^pay_[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Razorpay Signature ID format. Must followed hexadecimal HMAC-SHA256 signature.', regex='^[a-fA-F0-9]{64}$')]),
        ),
        migrations.AlterField(
            model_name='refund',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Invalid Razorpay Refund ID format. Must start with 'rfnd_' followed by alphanumeric characters.", regex='^rfnd_[A-Za-z0-9]+$')]),
        ),
    ]
