# Generated by Django 5.2.8 on 2026-02-13 13:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('staddr', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='Street-address')),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='City')),
                ('state', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='State')),
                ('hno', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='House no.')),
                ('landmark', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='Landmark')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
