# Generated by Django 5.2.8 on 2026-04-27 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hno',
            field=models.CharField(blank=True, default='', max_length=5, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='House no.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='location',
            name='staddr',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='Street-address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and ,' space are valid", regex="^[A-Za-z0-9,' ]+")], verbose_name='State'),
        ),
    ]
