# Generated by Django 5.2.8 on 2026-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0002_alter_location_city_alter_location_hno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_homeaddress',
            field=models.BooleanField(blank=True, default=False, verbose_name='is home address'),
        ),
    ]
