# Generated by Django 5.2.8 on 2026-08-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0004_alter_location_created_at_alter_location_updated_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('staddr', 'city', 'state', 'hno', 'landmark'), name='unique_full_location'),
        ),
    ]
