# Generated by Django 5.2.8 on 2026-08-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0005_location_unique_full_location'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_full_location',
        ),
    ]
