# Generated by Django 5.2.8 on 2026-09-08 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0006_remove_location_unique_full_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and .-' and space are valid", regex="^[A-Za-z.\\-' ]+")], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hno',
            field=models.CharField(blank=True, default='', max_length=5, validators=[django.core.validators.RegexValidator(message='only letters, numbers and .-/, and space are valid', regex='^[A-Za-z0-9-/., ]+')], verbose_name='House no.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and .,'/# and space are valid", regex="^[A-Za-z0-9.,\\-/#' ]+")], verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='location',
            name='staddr',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and .,'/# and space are valid", regex="^[A-Za-z0-9.,\\-/#' ]+")], verbose_name='Street-address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message="only letters and .-' and space are valid", regex="^[A-Za-z.\\-' ]+")], verbose_name='State'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('staddr', 'city', 'state', 'hno', 'landmark'), name='unique_full_location'),
        ),
    ]
